import json
from pathlib import Path
import importlib.util

spec = importlib.util.spec_from_file_location("top5", "build_top5_hotels.py")
top5 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(top5)

DATA = {
"empire-prestige-cwb": {
  "name": "香港銅鑼灣皇悅酒店（尚尊）Empire Prestige CWB",
  "en": "Empire Hotel Hong Kong - Causeway Bay (Prestige)",
  "address_zh": "香港銅鑼灣信德街33號",
  "address_en": "33 Hennessy Road, Causeway Bay, Hong Kong",
  "lat": 22.2791, "lng": 114.1810,
  "official": "https://www.empirehotelhk.com",
  "phone": "+852 3692 2333",
  "opened": "2013年",
  "rooms": 150,
  "district": "銅鑼灣",
  "mtr": "港鐵銅鑼灣站 A 出口步行約 3 分鐘",
  "intro": "銅鑼灣皇悅酒店（尚尊）位於銅鑼灣信德街，2013年開業，係皇悅集團旗下 4 星級精品酒店，150 間客房。距離時代廣場及崇光百貨步行 5 分鐘，購物交通極方便，適合商務及購物客。",
  "history": "皇悅集團係香港本地連鎖酒店品牌，在港有 5 間分店。銅鑼灣（尚尊）為集團高端線，主打商務客。",
  "facilities": ["24 小時健身中心", "商務中心", "免費 WiFi", "自助洗衣", "24小時前台"],
  "restaurants": ["The Plate — 全日餐廳", "大堂酒廊"],
  "rooms_info": "150 間客房，面積由 18 平方米（Standard）至 35 平方米（Suite）。房間現代簡約，配備 Smart TV、迷你吧、熨斗。",
  "price_range": "Standard Room HK$980 起 · Deluxe Room HK$1,380 起 · Suite HK$2,280 起",
  "nearby": ["時代廣場（步行 5 分鐘）", "崇光百貨 SOGO（步行 6 分鐘）", "維多利亞公園（步行 10 分鐘）", "利園區（步行 8 分鐘）", "跑馬地馬場（步行 12 分鐘）"],
  "tips": "皇悅尚尊地點靚價錢合理，適合預算中等嘅商務或購物客。房間較細但設施齊，免費 WiFi 穩定。",
  "faq": [
    ["皇悅尚尊點去？", "港鐵銅鑼灣站 A 出口沿軒尼詩道步行 3 分鐘，轉信德街即到。"],
    ["皇悅尚尊幾錢？", "Standard Room HK$980 起、Deluxe HK$1,380 起、Suite HK$2,280 起。"],
    ["皇悅尚尊房幾大？", "Standard 18 平方米較細，Deluxe 約 25 平方米較舒適，Suite 35 平方米可住 3 人。"],
    ["皇悅有幾間？", "皇悅集團在港有 5 間：銅鑼灣（尚尊）、灣仔、九龍、尖沙咀東、佐敦。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"],
    ["有泳池嗎？", "無。但設 24 小時健身中心供住客免費使用。"]
  ]
},
"nina-hotel-tsuen-wan-west": {
  "name": "香港如心酒店 Nina Hotel Tsuen Wan West",
  "en": "Nina Hotel Tsuen Wan West",
  "address_zh": "香港新界荃灣楊屋道8號",
  "address_en": "8 Yeung Uk Road, Tsuen Wan, New Territories, Hong Kong",
  "lat": 22.3721, "lng": 114.1065,
  "official": "https://www.ninahotel.com",
  "phone": "+852 2280 2000",
  "opened": "2006年（2019年翻新）",
  "rooms": 1608,
  "district": "荃灣",
  "mtr": "港鐵荃灣西站 A 出口有蓋天橋直達；荃灣站步行 15 分鐘",
  "intro": "香港如心酒店（Nina Hotel Tsuen Wan West）位於荃灣西站上蓋，2006年開業，擁有 1,608 間客房，係全港最大酒店。由華懋集團創辦人龔如心命名，2019年翻新後重新定位為 4 星級商務酒店。",
  "history": "前身為 Panda Hotel 同系品牌 L'hotel Nina et Convention Centre，2019年翻新後改名 Nina Hotel，主打年輕商務客及親子家庭。華懋集團旗下最大酒店資產。",
  "facilities": ["2 個戶外泳池（28米成人池＋兒童池）", "健身中心", "會議及宴會廳（最大 800 人）", "免費穿梭巴士往中環／尖沙咀／機場", "酒店商場"],
  "restaurants": ["The Patio — 全日自助餐", "Café Circles — 咖啡廳", "Lobby Lounge — 下午茶", "China Palace — 粵菜"],
  "rooms_info": "1,608 間客房，面積由 25 平方米（City Room）至 90 平方米（Suite）。翻新後設計年輕化，配備 Smart TV、Handy 智能手機。部分房型可賞青馬大橋及荃灣海景。",
  "price_range": "City Room HK$880 起 · Harbour View HK$1,280 起 · Suite HK$2,800 起",
  "nearby": ["荃新天地（同座）", "愉景新城（步行 10 分鐘）", "機場快綫青衣站（搭港鐵 1 站）", "迪士尼樂園（港鐵 25 分鐘）", "大嶼山昂坪 360（港鐵 30 分鐘）"],
  "tips": "如心酒店最大賣點係交通：荃灣西站上蓋，免費穿梭巴士往中環／尖沙咀／機場。適合預算中等、需要大空間、親子家庭旅客。平日房價可低至 HK$700+，極抵。",
  "faq": [
    ["如心酒店點去機場？", "搭免費穿梭巴士約 30 分鐘；或港鐵到青衣站轉機場快綫約 20 分鐘（HK$60）；的士約 30 分鐘、HK$220。"],
    ["如心酒店幾大？", "1,608 間客房，係全港最大酒店，佔地超過 32,000 平方米。"],
    ["如心酒店有泳池嗎？", "有 2 個戶外泳池（28 米成人池 + 兒童戲水池），位於 3 樓，6:30-22:00 開放，住客免費。"],
    ["如心酒店幾錢一晚？", "City Room HK$880 起、Harbour View HK$1,280 起、Suite HK$2,800 起。週末比平日貴 30%。"],
    ["如心酒店去迪士尼點去？", "港鐵荃灣綫荃灣西站 → 轉東涌綫 → 欣澳站 → 迪士尼綫，車程約 25 分鐘、HK$20。亦可搭的士約 20 分鐘。"],
    ["如心酒店適合親子嗎？", "非常適合。1,608 間房包括多款家庭套房，大型兒童泳池、免費 shuttle bus，荃新天地商場就喺樓下。"]
  ]
},
"sheraton-hong-kong": {
  "name": "香港喜來登酒店 Sheraton Hong Kong",
  "en": "Sheraton Hong Kong Hotel & Towers",
  "address_zh": "香港九龍尖沙咀彌敦道20號",
  "address_en": "20 Nathan Road, Tsim Sha Tsui, Kowloon, Hong Kong",
  "lat": 22.2957, "lng": 114.1721,
  "official": "https://www.marriott.com/hotels/travel/hkgsi-sheraton-hong-kong-hotel-and-towers",
  "phone": "+852 2369 1111",
  "opened": "1974年",
  "rooms": 782,
  "district": "尖沙咀",
  "mtr": "港鐵尖沙咀站 E 出口步行 3 分鐘",
  "intro": "香港喜來登酒店（Sheraton Hong Kong Hotel & Towers）位於尖沙咀彌敦道，1974年開業，擁有 782 間客房，係萬豪集團 Sheraton 品牌香港旗艦，緊鄰半島酒店，正對太空館及維港。經多次翻新，仍保持 5 星級商務酒店地位。",
  "history": "喜來登酒店1974年開業，當時為尖沙咀海傍新地標。2005、2017年進行兩次大型翻新。多年來接待無數名人及商務代表團。",
  "facilities": ["戶外恆溫泳池（4樓）", "Shine Spa 水療", "健身中心", "Towers 行政貴賓廊", "會議廳（最大 600 人）"],
  "restaurants": ["Morton's The Steakhouse — 美式扒房", "Unkai — 日本料理（獲米芝蓮推薦）", "Oyster & Wine Bar — 海鮮酒吧、18樓維港景", "Café Too — 全日自助餐", "Sky Lounge — 18樓雞尾酒吧"],
  "rooms_info": "782 間客房及套房，面積由 34 平方米（Deluxe）至 180 平方米（Presidential Suite）。2017年翻新後採現代風格，多數房型可賞維港景。",
  "price_range": "Deluxe Room HK$1,680 起 · Harbour View HK$2,800 起 · Presidential Suite HK$28,000 起",
  "nearby": ["半島酒店（步行 2 分鐘）", "海港城（步行 8 分鐘）", "星光大道（步行 5 分鐘）", "1881 Heritage（步行 5 分鐘）", "尖沙咀天星碼頭（步行 8 分鐘）"],
  "tips": "18 樓 Oyster & Wine Bar 同 Sky Lounge 可賞維港夜景，係打卡熱點。Morton's 美式扒房係香港最老字號之一。Marriott Bonvoy 會員可享 early/late check-out。",
  "faq": [
    ["喜來登同半島幾近？", "喜來登同半島酒店僅一街之隔（梳士巴利道 vs 彌敦道），步行 2 分鐘。價錢約半島一半，性價比更高。"],
    ["喜來登泳池點樣？", "4 樓戶外恆溫泳池，水溫 28°C，設兒童池、日光甲板、池邊酒吧。6:30-22:00 開放，住客免費。"],
    ["喜來登幾錢一晚？", "Deluxe HK$1,680 起、Harbour View HK$2,800 起、Presidential Suite HK$28,000 起。Bonvoy 會員額外折扣。"],
    ["喜來登附近食物？", "Morton's 扒房、Unkai 日式、Oyster Bar 海鮮；步行 2 分鐘到半島下午茶、5 分鐘到彌敦道茶餐廳。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：中午 12:00。"],
    ["喜來登有行政貴賓廊嗎？", "Towers 樓層客房（Club Room 起）享 Sheraton Club Lounge 貴賓廊：自助早餐、下午茶、happy hour。"]
  ]
},
"regala-skycity-hotel": {
  "name": "富薈機場酒店 Regala Skycity Hotel",
  "en": "Regala Skycity Hotel",
  "address_zh": "香港大嶼山赤鱲角航天城路 1 號",
  "address_en": "1 Sky City Road East, Lantau Island, Hong Kong",
  "lat": 22.3137, "lng": 113.9413,
  "official": "https://www.regalaskycityhotel.com",
  "phone": "+852 3658 0000",
  "opened": "2022年",
  "rooms": 1208,
  "district": "機場/赤鱲角",
  "mtr": "港鐵機場站，酒店免費穿梭巴士約 5 分鐘",
  "intro": "富薈機場酒店（Regala Skycity Hotel）位於香港國際機場 SKYCITY 航天城商業區，2022年開業，擁有 1,208 間客房，係香港最新機場酒店。由富豪國際酒店集團營運，設計年輕現代，大量客房可俯瞰機場跑道，係 avgeek（飛機迷）最愛。",
  "history": "SKYCITY 航天城係機場管理局發展嘅航空城綜合項目，富薈酒店係其中首批酒店之一，2022年6月開業。與機場客運大樓有接駁交通。",
  "facilities": ["觀景泳池（可賞機場跑道）", "健身中心", "商務中心", "會議廳", "24 小時免費機場穿梭巴士"],
  "restaurants": ["Oscar's — 全日自助餐", "Terminal A — 飛機主題餐廳酒吧", "大堂酒廊"],
  "rooms_info": "1,208 間客房，面積由 25 平方米（Superior）至 85 平方米（Suite）。部分房型為 Runway View Room（機場跑道景），可看飛機起降，打卡熱點。",
  "price_range": "Superior Room HK$680 起 · Runway View HK$980 起 · Suite HK$2,200 起",
  "nearby": ["香港國際機場（穿梭巴士 5 分鐘）", "Asia World-Expo 亞博（步行 8 分鐘）", "昂坪 360 纜車（車程 15 分鐘）", "大嶼山大佛（車程 20 分鐘）", "東涌東薈城名店倉（車程 10 分鐘）"],
  "tips": "Runway View Room 可賞 24 小時飛機起降景觀，飛機迷必揀。酒店 24 小時免費機場穿梭巴士，過境旅客首選。價錢比東涌其他機場酒店（Novotel、Regal）稍平。",
  "faq": [
    ["富薈點去機場？", "24 小時免費機場穿梭巴士約 5 分鐘，每 15-30 分鐘一班。亦可搭港鐵機場快綫到機場站一個站（HK$16）。"],
    ["富薈 Runway View 係咩？", "面向機場跑道嘅房型，大玻璃窗可看 24 小時飛機起降。適合飛機迷、長過境、親子看飛機。加價約 HK$250-400／晚。"],
    ["富薈幾錢一晚？", "Superior Room HK$680 起、Runway View HK$980 起、Suite HK$2,200 起。過境旅客平日最抵。"],
    ["富薈有泳池嗎？", "有。觀景泳池位於 9 樓，部分位置可賞機場跑道，只限住客免費使用。"],
    ["富薈適合長過境嗎？", "非常適合。24 小時穿梭巴士、可 day-use（部分套餐 6 小時 HK$450）、齊備餐飲。比返市區省時。"],
    ["富薈去迪士尼點去？", "搭港鐵機場站 → 欣澳站 → 迪士尼綫，車程約 15 分鐘、HK$20。酒店安排的士約 20 分鐘、HK$180。"]
  ]
},
"panda-hotel": {
  "name": "悅來酒店 Panda Hotel",
  "en": "Panda Hotel",
  "address_zh": "香港新界荃灣青山公路 3 號",
  "address_en": "3 Tsuen Wah Street, Tsuen Wan, New Territories, Hong Kong",
  "lat": 22.3713, "lng": 114.1188,
  "official": "https://www.pandahotel.com.hk",
  "phone": "+852 2409 1111",
  "opened": "1991年",
  "rooms": 1026,
  "district": "荃灣",
  "mtr": "港鐵荃灣站 A4 出口步行 5 分鐘；荃灣西站步行 10 分鐘",
  "intro": "悅來酒店（Panda Hotel）位於荃灣市中心，1991年開業，擁有 1,026 間客房，係香港第二大酒店（僅次於如心酒店）。由華懋集團興建營運，3 星級。以熊貓為主題，大堂設大型熊貓雕像，適合預算有限嘅親子旅客。",
  "history": "悅來酒店1991年開業，華懋集團旗下物業，係90年代香港最大酒店之一。2018年翻新公共空間及部分客房。",
  "facilities": ["戶外泳池（夏天開放）", "健身中心", "會議廳", "熊貓主題大堂", "酒店商場"],
  "restaurants": ["悅景軒 — 粵菜點心", "熊貓咖啡廳 — 全日自助餐", "The Deli — 輕食"],
  "rooms_info": "1,026 間客房，面積由 18 平方米（Standard）至 50 平方米（Family Suite）。房間實用基本型，部分翻新後較新。",
  "price_range": "Standard Room HK$580 起 · Superior Room HK$780 起 · Family Suite HK$1,380 起",
  "nearby": ["荃新天地（步行 8 分鐘）", "愉景新城（步行 15 分鐘）", "三棟屋博物館（步行 10 分鐘）", "荃灣海濱公園（步行 15 分鐘）", "如心酒店（步行 5 分鐘）"],
  "tips": "悅來酒店係荃灣最實惠嘅大型酒店之一，適合預算有限嘅親子及學生團。房間較老舊但設施齊。熊貓主題大堂係小朋友打卡點。如要更新嘅 4 星，加 HK$200 可揀同區如心酒店。",
  "faq": [
    ["悅來酒店點去？", "港鐵荃灣站 A4 出口沿青山公路步行 5 分鐘。亦有免費穿梭巴士往返機場、尖沙咀、中環。"],
    ["悅來酒店幾錢？", "Standard Room HK$580 起、Superior HK$780 起、Family Suite HK$1,380 起。係荃灣最抵大型酒店。"],
    ["悅來酒店有熊貓嗎？", "酒店以熊貓為主題，大堂設大型熊貓雕像、客房內有熊貓元素，但並無真熊貓。係小朋友打卡點。"],
    ["悅來酒店泳池幾時開？", "戶外泳池只於夏季（5-10 月）開放，6:30-21:00，住客免費。冬季關閉。"],
    ["悅來同如心點揀？", "悅來較平（HK$580 起 vs 如心 HK$880 起），但較舊；如心較新（2019 翻新）、房較大、設施更好。兩者相距步行 5 分鐘。"],
    ["悅來去迪士尼點去？", "港鐵荃灣站 → 荔景站轉東涌綫 → 欣澳站 → 迪士尼綫，車程 30 分鐘、HK$23。"]
  ]
},
"dorsett-wanchai": {
  "name": "香港灣仔帝盛酒店 Dorsett Wanchai",
  "en": "Dorsett Wanchai, Hong Kong",
  "address_zh": "香港灣仔皇后大道東387-397號",
  "address_en": "387-397 Queen's Road East, Wan Chai, Hong Kong",
  "lat": 22.2740, "lng": 114.1740,
  "official": "https://www.wanchai.dorsetthotels.com",
  "phone": "+852 3552 1111",
  "opened": "2014年",
  "rooms": 454,
  "district": "灣仔",
  "mtr": "港鐵灣仔站 A3 出口步行 8 分鐘；銅鑼灣站步行 12 分鐘",
  "intro": "香港灣仔帝盛酒店（Dorsett Wanchai, Hong Kong）位於灣仔皇后大道東，2014年開業，擁有 454 間客房，係帝盛集團旗下 4 星級商務酒店。近跑馬地馬場、利東街，設計年輕時尚。",
  "history": "灣仔帝盛2014年開業，由遠東發展旗下帝盛酒店集團營運。與集團其他 5 間酒店定位相似，中檔商務。",
  "facilities": ["頂層戶外泳池（41 樓、可賞維港）", "24 小時健身中心", "會議廳", "免費 Handy 智能手機", "商務中心"],
  "restaurants": ["Grand Café — 全日自助餐", "Sky Bar — 41樓天台酒吧、維港景"],
  "rooms_info": "454 間客房，面積由 22 平方米（Deluxe）至 65 平方米（Suite）。現代簡約設計，配備 Smart TV、Handy 智能手機。",
  "price_range": "Deluxe Room HK$1,180 起 · Executive Room HK$1,680 起 · Suite HK$2,880 起",
  "nearby": ["利東街（步行 5 分鐘）", "跑馬地馬場（步行 12 分鐘）", "太古廣場（步行 12 分鐘）", "香港會議展覽中心（步行 15 分鐘）", "藍屋（步行 3 分鐘）"],
  "tips": "灣仔帝盛 41 樓 Sky Bar 可賞維港夜景，係打卡熱點。每間房配免費 Handy 智能手機（打電話上網全免費）。酒店位置稍偏灣仔南，但近利東街及藍屋，文青路線首選。",
  "faq": [
    ["灣仔帝盛點去？", "港鐵灣仔站 A3 出口沿皇后大道東步行 8 分鐘；近藍屋及利東街。亦可搭電車或的士。"],
    ["灣仔帝盛 Sky Bar 幾高？", "Sky Bar 位於 41 樓天台，可 270° 俯瞰維港及灣仔。住客免費入內，非住客需消費。"],
    ["灣仔帝盛有手機？", "有。每間房配 Handy 智能手機，4G 上網及本地／國際通話全免費，外地旅客特別方便。"],
    ["灣仔帝盛幾錢？", "Deluxe HK$1,180 起、Executive HK$1,680 起、Suite HK$2,880 起。會展期間加 30-50%。"],
    ["附近有咩食？", "步行 5 分鐘利東街高級餐廳、3 分鐘藍屋舊式茶檔、8 分鐘到鵝頸橋米芝蓮推介牛雜麵。"],
    ["灣仔帝盛有泳池？", "有。41 樓戶外恆溫泳池，可俯瞰灣仔全景，6:30-21:30 開放，住客免費。"]
  ]
},
"hopewell-hotel": {
  "name": "合和酒店 Hopewell Hotel",
  "en": "Hopewell Hotel",
  "address_zh": "香港灣仔皇后大道東183號",
  "address_en": "183 Queen's Road East, Wan Chai, Hong Kong",
  "lat": 22.2745, "lng": 114.1738,
  "official": "https://www.hopewellhotel.com.hk",
  "phone": "+852 2832 2288",
  "opened": "2020年",
  "rooms": 1024,
  "district": "灣仔",
  "mtr": "港鐵灣仔站 A3 出口步行 10 分鐘；可乘酒店專車",
  "intro": "合和酒店（Hopewell Hotel）位於灣仔皇后大道東183號，2020年開業，擁有 1,024 間客房。由合和實業（胡應湘家族）興建，與合和中心二期 Hopewell Centre II（樓高55層）同座，係香港新代標誌建築之一。以灣仔山景及維港景為賣點。",
  "history": "合和酒店原計劃多年，因應環保及都更延期，終於2020年開業。係灣仔南最新大型發展項目。",
  "facilities": ["頂層泳池", "健身中心", "Spa 中心", "會議廳", "空中花園"],
  "restaurants": ["美食廣場（同座多間餐廳）", "Lobby Lounge"],
  "rooms_info": "1,024 間客房，面積由 28 平方米（Deluxe）至 150 平方米（Penthouse Suite）。新酒店設備最新，配備 Smart TV、Nespresso、落地玻璃窗。",
  "price_range": "Deluxe Room HK$1,380 起 · Harbour View HK$2,180 起 · Penthouse HK$8,800 起",
  "nearby": ["合和中心（同座）", "利東街（步行 5 分鐘）", "跑馬地馬場（步行 10 分鐘）", "藍屋（步行 3 分鐘）", "太古廣場（步行 15 分鐘）"],
  "tips": "合和酒店係香港最新大型酒店之一，設施最新。位置較高（山坡上），夜景景觀好。近利東街、藍屋，文青及外國遊客首選。",
  "faq": [
    ["合和酒店幾新？", "2020年開業，係灣仔最新大型酒店之一，所有設施都係最新。"],
    ["合和酒店點去？", "港鐵灣仔站 A3 出口沿皇后大道東上斜路步行 10 分鐘；或酒店免費穿梭巴士至地鐵站。"],
    ["合和酒店幾錢？", "Deluxe HK$1,380 起、Harbour View HK$2,180 起、Penthouse HK$8,800 起。"],
    ["合和有咩特別？", "合和中心二期（Hopewell Centre II）係灣仔新地標，樓高55層，酒店入住頂層，擁有維港及山景。"],
    ["附近景點？", "步行 3 分鐘藍屋（古蹟）、5 分鐘利東街（購物）、10 分鐘跑馬地馬場（賽馬）。"],
    ["有泳池嗎？", "有頂層景觀泳池及空中花園，住客免費使用。"]
  ]
},
"rosedale-hotel-hong-kong": {
  "name": "珀麗酒店 Rosedale Hotel Hong Kong",
  "en": "Rosedale Hotel Hong Kong",
  "address_zh": "香港銅鑼灣信德街8號",
  "address_en": "8 Shelter Street, Causeway Bay, Hong Kong",
  "lat": 22.2817, "lng": 114.1859,
  "official": "https://www.rosedale.com.hk/causewaybay",
  "phone": "+852 2127 8888",
  "opened": "2006年",
  "rooms": 274,
  "district": "銅鑼灣",
  "mtr": "港鐵銅鑼灣站 E 出口步行 5 分鐘；天后站步行 6 分鐘",
  "intro": "珀麗酒店（Rosedale Hotel Hong Kong）位於銅鑼灣信德街，2006年開業，擁有 274 間客房，係香港首間智能概念酒店，4 星級。由珀麗集團（麗新集團附屬）營運，房間設智能控制，適合商務客。",
  "history": "珀麗酒店2006年開業，定位「香港首間 eHotel 智能酒店」，房間配備當年先進嘅 infrared sensor、自動窗簾及溫控。2018年翻新。",
  "facilities": ["頂層觀景餐廳", "24 小時健身中心", "商務中心", "會議室", "免費 WiFi"],
  "restaurants": ["Sky Lounge — 頂層觀景餐廳", "全日咖啡廳"],
  "rooms_info": "274 間客房，面積由 18 平方米（Superior）至 45 平方米（Suite）。智能房間，配 Smart TV、自動窗簾、sensor 燈光。",
  "price_range": "Superior Room HK$780 起 · Deluxe HK$1,080 起 · Suite HK$1,880 起",
  "nearby": ["時代廣場（步行 8 分鐘）", "維多利亞公園（步行 5 分鐘）", "崇光百貨（步行 10 分鐘）", "利園區（步行 10 分鐘）", "跑馬地馬場（步行 12 分鐘）"],
  "tips": "珀麗銅鑼灣地點較接近維園一帶，安靜但近購物區。智能房設計雖然現已不算新，但房間翻新後仍保持現代感。性價比高。",
  "faq": [
    ["珀麗酒店點去？", "港鐵銅鑼灣站 E 出口沿告士打道步行 5 分鐘；天后站步行 6 分鐘。"],
    ["珀麗有幾間？", "珀麗集團在港有 3 間：銅鑼灣、九龍、中環（珀麗酒店中環）。"],
    ["珀麗酒店幾錢？", "Superior HK$780 起、Deluxe HK$1,080 起、Suite HK$1,880 起。銅鑼灣抵食之選。"],
    ["珀麗有泳池嗎？", "無泳池但有 24 小時健身中心。如要泳池可揀同區銅鑼灣皇冠假日或柏寧酒店。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"],
    ["附近餐廳？", "步行 8 分鐘到時代廣場美食廣場、10 分鐘崇光百貨超市、步行 5 分鐘即到維園口小食檔。"]
  ]
},
"empire-hotel-wan-chai": {
  "name": "香港灣仔皇悅酒店 Empire Hotel Wan Chai",
  "en": "Empire Hotel Hong Kong - Wan Chai",
  "address_zh": "香港灣仔軒尼詩道33號",
  "address_en": "33 Hennessy Road, Wan Chai, Hong Kong",
  "lat": 22.2775, "lng": 114.1733,
  "official": "https://www.empirehotelhk.com",
  "phone": "+852 3692 2111",
  "opened": "2000年",
  "rooms": 360,
  "district": "灣仔",
  "mtr": "港鐵灣仔站 A4 出口步行 3 分鐘",
  "intro": "香港灣仔皇悅酒店（Empire Hotel Hong Kong - Wan Chai）位於灣仔軒尼詩道，2000年開業，擁有 360 間客房，係皇悅集團旗下主力 4 星級商務酒店。地點方便，步行 5 分鐘到會展，商務客首選。",
  "history": "灣仔皇悅2000年開業，係皇悅集團在港首間酒店。2015年翻新部分房型。",
  "facilities": ["室內恆溫泳池", "24 小時健身中心", "商務中心", "會議廳（最大 200 人）", "大堂酒廊"],
  "restaurants": ["The Eight — 粵菜", "Café Plate — 全日餐廳", "La Bar — 酒吧"],
  "rooms_info": "360 間客房，面積由 20 平方米（Standard）至 55 平方米（Suite）。商務風格，配備 Smart TV、免費 WiFi、保險箱。",
  "price_range": "Standard Room HK$980 起 · Deluxe HK$1,280 起 · Suite HK$2,280 起",
  "nearby": ["會議展覽中心（步行 8 分鐘）", "金紫荊廣場（步行 10 分鐘）", "利東街（步行 3 分鐘）", "太古廣場（步行 15 分鐘）", "藍屋（步行 5 分鐘）"],
  "tips": "灣仔皇悅位置佳，近會展，適合商務出差。會展期間（書展、動漫節等）經常客滿，建議提早 1-2 個月預訂。",
  "faq": [
    ["灣仔皇悅點去會展？", "步行 8 分鐘沿軒尼詩道、港灣道前往；或搭的士約 5 分鐘。"],
    ["灣仔皇悅幾錢？", "Standard HK$980 起、Deluxe HK$1,280 起、Suite HK$2,280 起。會展期加 40-70%。"],
    ["灣仔皇悅有泳池？", "有。室內恆溫泳池，水溫 28°C，6:30-22:00，住客免費。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"],
    ["附近有咩食？", "步行 3 分鐘利東街餐廳、5 分鐘軒尼詩道茶餐廳、10 分鐘官塘古惑仔火鍋。"],
    ["皇悅集團有幾多間？", "皇悅集團在港 5 間：灣仔、銅鑼灣（尚尊）、九龍、尖沙咀東、佐敦。"]
  ]
},
"maple-leaf-hotel": {
  "name": "楓葉酒店 Maple Leaf Hotel",
  "en": "Maple Leaf Hotel",
  "address_zh": "香港灣仔駱克道300號",
  "address_en": "300 Lockhart Road, Wan Chai, Hong Kong",
  "lat": 22.2784, "lng": 114.1751,
  "official": "https://www.mapleleafhotel.com.hk",
  "phone": "+852 2866 2188",
  "opened": "2017年",
  "rooms": 88,
  "district": "灣仔",
  "mtr": "港鐵灣仔站 C 出口步行 5 分鐘",
  "intro": "楓葉酒店（Maple Leaf Hotel）位於灣仔駱克道，2017年開業，擁有 88 間客房，係小型精品 3 星級酒店。地點方便，近會展及商業區，房間雖然較細但價錢抵。",
  "history": "楓葉酒店2017年開業，係灣仔眾多小型精品酒店之一，由本地投資者營運。",
  "facilities": ["24 小時前台", "免費 WiFi", "迷你商務角", "禁煙樓層"],
  "restaurants": ["附近多茶餐廳、日式、韓式餐廳"],
  "rooms_info": "88 間客房，面積由 12 平方米（Economy）至 22 平方米（Deluxe）。房間精簡，設空調、免費 WiFi、LCD 電視、迷你雪櫃。",
  "price_range": "Economy Room HK$480 起 · Standard HK$580 起 · Deluxe HK$780 起",
  "nearby": ["會議展覽中心（步行 10 分鐘）", "時代廣場（步行 12 分鐘）", "利東街（步行 8 分鐘）", "駱克道酒吧街（步行 2 分鐘）", "太古廣場（步行 15 分鐘）"],
  "tips": "楓葉酒店係經濟型選擇，房間細但位置佳、乾淨。適合預算有限嘅短期過境或商務客。駱克道多酒吧食肆。",
  "faq": [
    ["楓葉酒店點去？", "港鐵灣仔站 C 出口沿駱克道步行 5 分鐘。"],
    ["楓葉房間幾大？", "Economy 12 平方米、Standard 15 平方米、Deluxe 22 平方米。屬於細房精品。"],
    ["楓葉幾錢？", "Economy HK$480 起、Standard HK$580 起、Deluxe HK$780 起。灣仔平價選擇。"],
    ["楓葉有泳池？", "無。精品小酒店無泳池。如要可揀同區灣仔帝盛或灣仔皇悅。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"],
    ["附近有咩？", "駱克道酒吧街，步行 2 分鐘；會展 10 分鐘；時代廣場 12 分鐘。"]
  ]
}
}

for slug,d in DATA.items():
    Path(f'pages/hotels/{slug}.html').write_text(top5.render(slug,d),encoding='utf-8')
    print('ok',slug)
