import json
from pathlib import Path
import importlib.util

spec = importlib.util.spec_from_file_location("top5", "build_top5_hotels.py")
top5 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(top5)

DATA = {
"royal-garden-hotel": {
  "name": "帝苑酒店 Royal Garden Hotel",
  "en": "The Royal Garden Hotel",
  "address_zh": "香港九龍尖沙咀東部麼地道69號",
  "address_en": "69 Mody Road, Tsim Sha Tsui East, Kowloon, Hong Kong",
  "lat": 22.2992, "lng": 114.1785,
  "official": "https://www.rghk.com.hk",
  "phone": "+852 2721 5215",
  "opened": "1981年",
  "rooms": 420,
  "district": "尖沙咀東",
  "mtr": "港鐵尖東站 P1 出口步行 3 分鐘",
  "intro": "帝苑酒店（The Royal Garden Hotel）位於尖沙咀東部麼地道，1981年開業，擁有 420 間客房，係信和集團旗下 5 星級酒店。以中庭大花園及羅馬式頂層泳池聞名，係香港經典酒店之一。",
  "history": "帝苑酒店1981年開業，係信和集團（黃廷方家族）旗下首間酒店，2013年翻新。以中庭綠化花園著稱，每晚有現場鋼琴音樂。",
  "facilities": ["羅馬式頂層恆溫泳池（25米）", "健身中心", "天然光中庭花園", "Spa", "會議宴會廳"],
  "restaurants": ["Dong Lai Shun 東來順 — 北京菜", "Sabatini — 意大利菜（米芝蓮推介）", "Le Soleil — 越南菜", "Lobby Lounge — 下午茶"],
  "rooms_info": "420 間客房，面積由 34 平方米至 150 平方米。中庭花園景房特別寧靜，配備 Smart TV、Nespresso。",
  "price_range": "Deluxe Room HK$1,580 起 · Premier HK$2,280 起 · Suite HK$6,800 起",
  "nearby": ["香港歷史博物館（步行 3 分鐘）", "香港科學館（步行 3 分鐘）", "紅磡體育館（步行 10 分鐘）", "K11 MUSEA（步行 10 分鐘）", "尖東海濱（步行 5 分鐘）"],
  "tips": "Sabatini 意大利菜係香港最老牌米芝蓮推介意菜之一，羅馬總店直接分號。中庭花園每晚有現場鋼琴音樂，下午茶氣氛特別優雅。",
  "faq": [
    ["帝苑點去？", "港鐵尖東站 P1 出口沿麼地道步行 3 分鐘。"],
    ["帝苑有咩出名？", "中庭大花園、羅馬式頂層泳池、Sabatini 意大利菜（米芝蓮推介）、Dong Lai Shun 北京菜。"],
    ["帝苑幾錢？", "Deluxe HK$1,580 起、Premier HK$2,280 起、Suite HK$6,800 起。"],
    ["帝苑泳池幾時開？", "頂層 25 米恆溫泳池，6:30-22:00，住客免費。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：中午 12:00。"],
    ["帝苑同帝樂差別？", "帝苑（Royal Garden）係尖東 5 星老牌；帝樂（Luxe Manor）係尖東精品酒店。兩者均信和集團旗下。"]
  ]
},
"empire-hotel-cwb": {
  "name": "香港銅鑼灣皇悅酒店 Empire Hotel CWB",
  "en": "Empire Hotel Hong Kong - Causeway Bay",
  "address_zh": "香港銅鑼灣禮頓道8號",
  "address_en": "8 Leighton Road, Causeway Bay, Hong Kong",
  "lat": 22.2778, "lng": 114.1842,
  "official": "https://www.empirehotelhk.com",
  "phone": "+852 3692 2222",
  "opened": "2006年",
  "rooms": 348,
  "district": "銅鑼灣",
  "mtr": "港鐵銅鑼灣站 F 出口步行 5 分鐘",
  "intro": "香港銅鑼灣皇悅酒店（Empire Hotel Hong Kong - Causeway Bay）位於銅鑼灣禮頓道，2006年開業，擁有 348 間客房。4 星級商務酒店，近時代廣場及跑馬地。",
  "history": "銅鑼灣皇悅2006年開業，係皇悅集團在港第二間分店。",
  "facilities": ["室內泳池", "24 小時健身中心", "商務中心", "會議廳"],
  "restaurants": ["Cafe Plate — 全日餐廳", "Lobby Lounge"],
  "rooms_info": "348 間客房，面積由 20 平方米至 45 平方米，商務風格。",
  "price_range": "Standard HK$880 起 · Deluxe HK$1,180 起 · Suite HK$1,980 起",
  "nearby": ["時代廣場（步行 8 分鐘）", "崇光百貨（步行 10 分鐘）", "跑馬地馬場（步行 10 分鐘）", "利園區（步行 3 分鐘）", "維多利亞公園（步行 12 分鐘）"],
  "tips": "皇悅銅鑼灣位置非常接近銅鑼灣皇冠假日（同一條禮頓道），價錢比皇冠抵約 30%，性價比高。",
  "faq": [
    ["皇悅銅鑼灣點去？", "港鐵銅鑼灣站 F 出口沿禮頓道步行 5 分鐘。"],
    ["皇悅銅鑼灣幾錢？", "Standard HK$880 起、Deluxe HK$1,180 起、Suite HK$1,980 起。"],
    ["皇悅有泳池嗎？", "有。室內泳池，6:30-22:00，住客免費。"],
    ["附近有咩？", "步行 3 分鐘利園區、8 分鐘時代廣場、10 分鐘跑馬地馬場。"],
    ["皇悅幾間分店？", "皇悅集團在港 5 間：銅鑼灣、灣仔、九龍、尖沙咀東、佐敦。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"]
  ]
},
"conrad-hong-kong": {
  "name": "港麗酒店 Conrad Hong Kong",
  "en": "Conrad Hong Kong",
  "address_zh": "香港金鐘金鐘道88號太古廣場",
  "address_en": "88 Queensway, Admiralty, Hong Kong",
  "lat": 22.2779, "lng": 114.1645,
  "official": "https://www.hilton.com/en/hotels/hkghccv-conrad-hong-kong",
  "phone": "+852 2521 3838",
  "opened": "1990年",
  "rooms": 512,
  "district": "金鐘",
  "mtr": "港鐵金鐘站 F 出口經太古廣場直達",
  "intro": "港麗酒店（Conrad Hong Kong）位於金鐘太古廣場上蓋，1990年開業，擁有 512 間客房，係希爾頓集團 Conrad 品牌香港旗艦。地點優越，與太古廣場及立法會大樓相連，商務客首選。",
  "history": "港麗酒店1990年開業，入住太古廣場綜合建築 40-61 樓。2017年進行大型翻新。2023年再進行客房升級。",
  "facilities": ["戶外恆溫泳池（11樓、望維港）", "健身中心 24 小時", "Conrad Spa", "Executive Lounge 貴賓廊", "會議廳"],
  "restaurants": ["Golden Leaf 金葉庭 — 米芝蓮粵菜", "Nicholini's — 意大利菜", "Garden Café — 全日自助餐", "Lobby Lounge — 下午茶"],
  "rooms_info": "512 間客房，面積由 43 平方米至 270 平方米。2017 翻新後採現代奢華風，部分房型可賞維港全景。",
  "price_range": "Deluxe Room HK$2,600 起 · Harbour View HK$3,800 起 · Presidential Suite HK$48,000 起",
  "nearby": ["太古廣場（直通）", "政府總部（步行 5 分鐘）", "香港公園（步行 3 分鐘）", "中環半山自動扶梯（步行 10 分鐘）", "維多利亞港金鐘碼頭（步行 8 分鐘）"],
  "tips": "港麗連接太古廣場，購物用餐極便利。Golden Leaf 米芝蓮粵菜性價比高，午市點心 HK$388 起。Executive Floor（行政樓層）升級可享貴賓廊自助早餐、下午茶、happy hour。",
  "faq": [
    ["港麗酒店點去？", "港鐵金鐘站 F 出口經太古廣場商場直達酒店大堂，無需過馬路。"],
    ["港麗有咩米芝蓮？", "Golden Leaf 金葉庭粵菜、Nicholini's 意大利菜均獲米芝蓮推介。"],
    ["港麗幾錢一晚？", "Deluxe HK$2,600 起、Harbour View HK$3,800 起、Presidential Suite HK$48,000 起。"],
    ["港麗同君悅點揀？", "港麗在金鐘（太古廣場上蓋、購物便利），君悅在灣仔（會展旁邊、花園大）。商務會展揀君悅，購物商務揀港麗。"],
    ["港麗有泳池？", "有。11 樓戶外恆溫泳池可賞維港，6:30-22:00，住客免費。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：中午 12:00。Hilton Honors Gold 以上會員可享免費 late check-out。"]
  ]
},
"kerry-hotel-hong-kong": {
  "name": "香港嘉里酒店 Kerry Hotel Hong Kong",
  "en": "Kerry Hotel, Hong Kong",
  "address_zh": "香港九龍紅磡紅鸞道38號",
  "address_en": "38 Hung Luen Road, Hung Hom Bay, Kowloon, Hong Kong",
  "lat": 22.3050, "lng": 114.1904,
  "official": "https://www.shangri-la.com/hongkong/kerry",
  "phone": "+852 2252 5888",
  "opened": "2017年4月",
  "rooms": 546,
  "district": "紅磡",
  "mtr": "港鐵紅磡站步行 15 分鐘；酒店設免費穿梭巴士往尖沙咀／中環／機場",
  "intro": "香港嘉里酒店（Kerry Hotel, Hong Kong）位於紅磡海濱紅鸞道，2017年4月開業，擁有 546 間客房。香格里拉集團 Kerry 品牌香港旗艦，係香港首間城市度假酒店，擁有全港最長酒店海濱沙灘。",
  "history": "嘉里酒店2017年開業，由郭氏家族嘉里集團興建（香格里拉姊妹品牌），入住紅磡灣填海區。",
  "facilities": ["全港最長戶外無邊際泳池（25米）", "私人海濱沙灘及公園（200米）", "Kerry Spa", "健身中心", "兒童樂園及 Kids Club", "會議廳"],
  "restaurants": ["Hung Tong 紅糖 — 粵菜", "Big Bay Cafe — 全日自助餐（海景）", "Red Sugar — 露台酒吧（海濱）", "Dockyard — 美食廣場概念"],
  "rooms_info": "546 間客房及套房，面積由 42 平方米（Deluxe）至 213 平方米（Presidential Suite）。超過 80% 房型擁海景露台，配備落地玻璃窗、Nespresso、深泡浴缸。",
  "price_range": "Deluxe Room HK$2,200 起 · Harbour View HK$3,500 起 · Presidential Suite HK$38,000 起",
  "nearby": ["紅磡海濱長廊（酒店即出）", "紅磡火車站（步行 15 分鐘）", "香港理工大學（步行 15 分鐘）", "黃埔花園（步行 20 分鐘）", "尖沙咀（的士 10 分鐘）"],
  "tips": "嘉里酒店係香港唯一城市度假酒店（Staycation 熱門首選），戶外無邊際泳池、私人沙灘、露天酒吧景觀一流。Red Sugar 露台酒吧賞維港落日絕景。免費穿梭巴士往尖沙咀／中環方便。",
  "faq": [
    ["嘉里酒店位於邊度？", "紅磡海濱紅鸞道38號，面向維多利亞港，係填海發展區。"],
    ["嘉里點去？", "酒店提供免費穿梭巴士往返尖沙咀／中環／機場。港鐵紅磡站步行 15 分鐘；或的士 5 分鐘。"],
    ["嘉里適合 Staycation 嗎？", "最適合。香港唯一城市度假酒店，有私人沙灘、200米海濱公園、全港最長泳池、Kids Club、海景房。週末 Staycation 熱門。"],
    ["嘉里幾錢一晚？", "Deluxe HK$2,200 起、Harbour View HK$3,500 起、Presidential Suite HK$38,000 起。週末加 30-50%。"],
    ["嘉里泳池幾長？", "25 米戶外無邊際泳池係全港最長酒店泳池，水溫 28°C，全日光甲板，6:30-22:00 開放。"],
    ["嘉里附近有咩？", "紅磡海濱長廊、紅磡體育館、香港理工大學、黃埔花園商場。的士 10 分鐘到尖沙咀，交通方便。"]
  ]
},
"hk-disneyland-hotel": {
  "name": "香港迪士尼樂園酒店 HK Disneyland Hotel",
  "en": "Hong Kong Disneyland Hotel",
  "address_zh": "香港大嶼山香港迪士尼樂園度假區",
  "address_en": "Hong Kong Disneyland Resort, Lantau Island, Hong Kong",
  "lat": 22.3131, "lng": 114.0389,
  "official": "https://www.hongkongdisneyland.com/hotels",
  "phone": "+852 3510 6000",
  "opened": "2005年9月",
  "rooms": 400,
  "district": "大嶼山/迪士尼",
  "mtr": "港鐵迪士尼綫迪士尼站，酒店提供免費穿梭巴士",
  "intro": "香港迪士尼樂園酒店（Hong Kong Disneyland Hotel）位於大嶼山迪士尼度假區，2005年9月開業，擁有 400 間客房，係迪士尼樂園園區官方酒店。維多利亞式建築，設計彰顯奢華童話風格，係迪士尼迷首選。",
  "history": "迪士尼樂園酒店同樂園同步於2005年9月開業，係香港迪士尼度假區三間酒店中最豪華嘅一間（另有探索家度假酒店、荷里活酒店）。",
  "facilities": ["室內恆溫泳池（玻璃天花）", "戶外泳池 Mickey 造型", "Kids Club", "迷宮花園", "健身中心", "會議廳", "24 小時往返樂園嘅免費穿梭巴士"],
  "restaurants": ["Crystal Lotus — 米芝蓮推介粵菜（迪士尼主題點心）", "Enchanted Garden — 全日自助餐（角色見面）", "Walt's Cafe — 輕食"],
  "rooms_info": "400 間客房及套房，維多利亞式設計，面積由 35 平方米（Standard）至 2,000 平方米（Walt's Suite）。部分房型 Harbour View 可賞深水灣海景。",
  "price_range": "Standard Room HK$2,200 起 · Sea View HK$3,200 起 · Walt's Suite HK$50,000 起",
  "nearby": ["香港迪士尼樂園（免費穿梭巴士 5 分鐘）", "樂園迪欣湖活動中心（步行 10 分鐘）", "愉景灣（的士 15 分鐘）", "東涌東薈城（港鐵 15 分鐘）", "機場（的士 15 分鐘）"],
  "tips": "迪士尼酒店住客可享「官方酒店優惠」：免費穿梭巴士、園區優先 check-in、角色見面等。Enchanted Garden 自助餐有米奇、美妮現身，親子首選。建議預訂含門票嘅套票（住宿+2天門票+自助早餐）更抵。",
  "faq": [
    ["迪士尼酒店點去樂園？", "免費穿梭巴士 5 分鐘；或步行 20 分鐘經迪欣湖畔。"],
    ["迪士尼酒店有咩獨享？", "住客可享：園區優先入園、快速通行優先、Enchanted Garden 角色見面自助早餐、免費樂園穿梭巴士。"],
    ["迪士尼酒店幾錢？", "Standard HK$2,200 起、Sea View HK$3,200 起、Walt's Suite HK$50,000 起。套票（住宿+2天門票）通常較單買抵 20-30%。"],
    ["迪士尼三間酒店點揀？", "迪士尼樂園酒店（最豪華、維多利亞風）；探索家度假酒店（探險主題、較新 2017）；荷里活酒店（平價、音樂主題）。價差約 HK$500-1,500。"],
    ["迪士尼酒店去機場點去？", "的士約 15 分鐘、HK$150-200；或港鐵迪士尼線→欣澳→機場站，車程 25 分鐘、HK$25。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：上午 11:00（迪士尼酒店較早）。樂園門票持有者可 early access 至樂園。"]
  ]
},
"new-world-millennium-hk": {
  "name": "千禧新世界香港酒店 New World Millennium HK",
  "en": "New World Millennium Hong Kong Hotel",
  "address_zh": "香港九龍尖沙咀東部麼地道72號",
  "address_en": "72 Mody Road, Tsim Sha Tsui East, Kowloon, Hong Kong",
  "lat": 22.2993, "lng": 114.1791,
  "official": "https://www.newworldmillenniumhotel.com",
  "phone": "+852 2739 1111",
  "opened": "1981年（2008年重新翻新）",
  "rooms": 464,
  "district": "尖沙咀東",
  "mtr": "港鐵尖東站 P2 出口步行 5 分鐘",
  "intro": "千禧新世界香港酒店（New World Millennium Hong Kong Hotel）位於尖沙咀東部麼地道，1981年開業，2008年翻新，擁有 464 間客房，係新世界發展（鄭家純家族）旗下 5 星級酒店。鄰近紅磡體育館、維港海濱。",
  "history": "酒店1981年開業，原名 New World Hotel，2008年完成大型翻新並改名 Millennium。新世界集團旗下「新世界酒店」同「千禧新世界」係兩個品牌。",
  "facilities": ["戶外恆溫泳池", "Fitness First 健身中心", "Spa", "會議宴會廳（最大 400 人）", "商務中心"],
  "restaurants": ["Sagano 嵯峨野 — 日本料理", "Tao Li 桃李 — 粵菜", "The Residence — 全日自助餐", "The Lobby Lounge — 下午茶"],
  "rooms_info": "464 間客房，面積由 30 平方米至 120 平方米。2008 翻新後採當代簡約風，配備 Smart TV、Nespresso。部分房可賞維港景。",
  "price_range": "Superior Room HK$1,380 起 · Harbour View HK$2,180 起 · Suite HK$5,800 起",
  "nearby": ["香港歷史博物館（步行 3 分鐘）", "紅磡體育館（步行 8 分鐘）", "K11 MUSEA（步行 10 分鐘）", "尖東海濱（步行 5 分鐘）", "半島酒店（步行 12 分鐘）"],
  "tips": "千禧新世界近紅磡體育館，演唱會散場後回酒店步行 8 分鐘，方便歌迷。Tao Li 桃李粵菜午市點心套餐較抵。",
  "faq": [
    ["千禧新世界點去？", "港鐵尖東站 P2 出口沿麼地道步行 5 分鐘。"],
    ["千禧新世界幾錢？", "Superior HK$1,380 起、Harbour View HK$2,180 起、Suite HK$5,800 起。"],
    ["千禧近紅館嗎？", "步行 8 分鐘到紅磡體育館，係睇演唱會首選住宿。"],
    ["新世界同千禧點分？", "新世界酒店（New World Hotel）係高端品牌，目前香港無；千禧新世界（New World Millennium）係中高端商務品牌，尖東旗艦。"],
    ["有泳池嗎？", "有戶外恆溫泳池，6:30-22:00，住客免費。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：中午 12:00。"]
  ]
},
"royal-plaza-hotel": {
  "name": "帝京酒店 Royal Plaza Hotel",
  "en": "Royal Plaza Hotel",
  "address_zh": "香港九龍旺角太子道西193號",
  "address_en": "193 Prince Edward Road West, Mongkok, Kowloon, Hong Kong",
  "lat": 22.3255, "lng": 114.1708,
  "official": "https://www.royalplaza.com.hk",
  "phone": "+852 2928 8822",
  "opened": "1995年",
  "rooms": 699,
  "district": "旺角/太子",
  "mtr": "港鐵旺角東站步行 1 分鐘（直通商場）",
  "intro": "帝京酒店（Royal Plaza Hotel）位於旺角太子道西，1995年開業，擁有 699 間客房。4 星級，由九龍巴士（九巴母公司載通）興建，港鐵旺角東站上蓋，直通 MOKO 新世紀廣場，交通極便利。",
  "history": "帝京酒店1995年開業，由載通國際（九巴母公司）發展。2019年翻新部分樓層及公共空間。",
  "facilities": ["戶外恆溫泳池（40米，全港最大酒店戶外泳池之一）", "健身中心", "Spa", "會議廳（最大 700 人）", "MOKO 新世紀廣場（相連）"],
  "restaurants": ["La Scala — 意大利菜", "Dragon Seal 龍皇 — 粵菜", "Café Royal — 全日自助餐", "Lobby Lounge"],
  "rooms_info": "699 間客房，面積由 29 平方米（Superior）至 100 平方米（Suite）。2019 翻新後採現代商務風。",
  "price_range": "Superior Room HK$980 起 · Deluxe Room HK$1,380 起 · Suite HK$3,800 起",
  "nearby": ["MOKO 新世紀廣場（直通）", "旺角購物區（步行 5 分鐘）", "花墟公園（步行 10 分鐘）", "女人街（步行 10 分鐘）", "通菜街金魚街（步行 10 分鐘）"],
  "tips": "帝京交通極佳：港鐵旺角東站直通、東鐵綫 1 站到紅磡、2 站到尖沙咀。40 米戶外泳池全年恆溫，係尖沙咀外最大酒店泳池。商場直通方便購物用餐。",
  "faq": [
    ["帝京點去？", "港鐵旺角東站下車，經 MOKO 新世紀廣場商場直通酒店，步行 1 分鐘，大行李最方便。"],
    ["帝京幾錢？", "Superior HK$980 起、Deluxe HK$1,380 起、Suite HK$3,800 起。性價比高。"],
    ["帝京泳池幾大？", "40 米戶外恆溫泳池，全年開放，係旺角區最大酒店泳池。6:30-22:00，住客免費。"],
    ["帝京近邊到？", "旺角購物區（花墟、女人街、金魚街、波鞋街）、MOKO 商場、太子食街。"],
    ["帝京去機場？", "港鐵 3 個站到青衣轉機場快綫，總車程 40 分鐘、HK$80；或的士約 35 分鐘、HK$280。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"]
  ]
},
"four-points-tung-chung": {
  "name": "香港東涌福朋喜來登酒店 Four Points Tung Chung",
  "en": "Four Points by Sheraton Hong Kong, Tung Chung",
  "address_zh": "香港大嶼山東涌達東路51號",
  "address_en": "51 Tat Tung Road, Tung Chung, Lantau Island, Hong Kong",
  "lat": 22.2870, "lng": 113.9427,
  "official": "https://www.marriott.com/hotels/travel/hkgfp-four-points-by-sheraton-hong-kong-tung-chung",
  "phone": "+852 3693 6666",
  "opened": "2017年",
  "rooms": 530,
  "district": "東涌",
  "mtr": "港鐵東涌站 B 出口步行 8 分鐘；機場快綫博覽館站步行 15 分鐘",
  "intro": "香港東涌福朋喜來登酒店（Four Points by Sheraton Hong Kong, Tung Chung）位於大嶼山東涌達東路，2017年開業，擁有 530 間客房，係萬豪集團 Four Points 品牌香港旗艦。近機場、迪士尼、昂坪纜車，4 星級。",
  "history": "東涌福朋2017年開業，隨東涌東薈城擴建及機場業務增長而興建。",
  "facilities": ["室內溫水泳池", "健身中心 24 小時", "商務中心", "會議廳", "24 小時免費機場穿梭巴士"],
  "restaurants": ["The Best Brew — 精釀啤酒吧", "Beachside Bar & Grill — 全日餐廳", "Sunday Brunch — 週末自助餐"],
  "rooms_info": "530 間客房，面積由 34 平方米至 70 平方米。Four Points 標準商務風格，配備 Smart TV、Nespresso 咖啡機。",
  "price_range": "Deluxe Room HK$880 起 · Family Room HK$1,280 起 · Suite HK$2,800 起",
  "nearby": ["東涌東薈城名店倉（步行 5 分鐘）", "東薈城（步行 3 分鐘）", "昂坪 360 纜車東涌站（步行 10 分鐘）", "香港國際機場（穿梭巴士 15 分鐘）", "迪士尼（港鐵 10 分鐘）"],
  "tips": "東涌福朋係去機場／迪士尼／大佛昂坪嘅最佳中轉站。24 小時機場穿梭巴士方便過境。東薈城 Outlet 購物超抵（品牌 3-7 折）。",
  "faq": [
    ["東涌福朋去機場？", "24 小時免費穿梭巴士 15 分鐘；或港鐵東涌站 → 青衣 → 機場快綫，30 分鐘、HK$75。"],
    ["東涌福朋幾錢？", "Deluxe HK$880 起、Family Room HK$1,280 起、Suite HK$2,800 起。係機場酒店中較抵選擇。"],
    ["東涌福朋去昂坪？", "步行 10 分鐘到昂坪 360 東涌纜車站，纜車 25 分鐘到昂坪大佛，來回約 HK$298。"],
    ["東涌福朋去迪士尼？", "港鐵東涌綫東涌 → 欣澳 → 迪士尼綫，10 分鐘、HK$13。比酒店穿梭巴士方便。"],
    ["東涌福朋適合親子？", "非常適合。家庭套房（70 平方米可住 4 人）、Kids Club、室內泳池、近東薈城兒童遊樂區。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：中午 12:00。"]
  ]
},
"regal-airport-hotel": {
  "name": "富豪機場酒店 Regal Airport Hotel",
  "en": "Regal Airport Hotel",
  "address_zh": "香港大嶼山赤鱲角機場路9號",
  "address_en": "9 Cheong Tat Road, Hong Kong International Airport, Lantau, Hong Kong",
  "lat": 22.3161, "lng": 113.9415,
  "official": "https://www.regalhotel.com/regal-airport-hotel",
  "phone": "+852 2286 8888",
  "opened": "1998年（與機場同步開幕）",
  "rooms": 1171,
  "district": "機場/赤鱲角",
  "mtr": "機場離境大堂直通（經有蓋行人天橋步行 3 分鐘）",
  "intro": "富豪機場酒店（Regal Airport Hotel）位於香港國際機場旁，1998年與機場同步開業，擁有 1,171 間客房，係全港最大酒店之一，亦係最近機場嘅酒店。富豪國際酒店集團旗艦物業。",
  "history": "富豪機場酒店1998年7月6日與香港國際機場同步開業，係全港首間真正直通機場嘅酒店，服務全球過境旅客。",
  "facilities": ["戶外無邊際泳池（望機場跑道）", "健身中心", "多間會議廳（最大 1,000 人）", "Regal Spa", "免費機場穿梭服務"],
  "restaurants": ["Rouge — 法式扒房", "Dragon Inn 龍門 — 粵菜酒家（大型茶樓）", "Café Aficionado — 全日自助餐", "大堂酒廊"],
  "rooms_info": "1,171 間客房，面積由 30 平方米至 220 平方米。部分房型面向機場跑道（Runway View），可看 24 小時飛機起降。",
  "price_range": "Superior Room HK$880 起 · Runway View HK$1,280 起 · Suite HK$3,800 起",
  "nearby": ["香港國際機場（行人天橋 3 分鐘）", "亞博館（車程 10 分鐘）", "昂坪 360（車程 20 分鐘）", "東薈城（車程 10 分鐘）", "迪士尼（車程 15 分鐘）"],
  "tips": "富豪機場酒店係唯一真正步行直通機場嘅酒店（有蓋天橋 3 分鐘），長過境或清晨航班首選。Day-use（6小時）套餐約 HK$380-580。Dragon Inn 龍門大型茶樓係 avgeek 熱點，可邊飲茶邊看飛機。",
  "faq": [
    ["富豪機場酒店去機場？", "有蓋行人天橋步行 3 分鐘直達離境大堂。係全港最方便機場嘅酒店。"],
    ["富豪機場酒店有 Day-use？", "有。提供 6 小時、12 小時 day-use 套餐約 HK$380-880，適合長過境、延誤、清晨航班。"],
    ["富豪機場 vs 富薈機場點揀？", "富豪（1998年）較老但行人天橋直達機場；富薈（2022年）較新但穿梭巴士 5 分鐘。富豪較近機場但設施較舊，富薈較新但稍遠。"],
    ["富豪機場幾錢？", "Superior HK$880 起、Runway View HK$1,280 起、Suite HK$3,800 起。"],
    ["Runway View 值唔值？", "飛機迷及打卡必選。24 小時看飛機起降，加價約 HK$300-400／晚，值得。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。可付費 early check-in／late check-out。"]
  ]
},
"the-harbourview": {
  "name": "灣景國際 The Harbourview",
  "en": "The Harbourview",
  "address_zh": "香港灣仔港灣道4號",
  "address_en": "4 Harbour Road, Wan Chai, Hong Kong",
  "lat": 22.2813, "lng": 114.1729,
  "official": "https://www.theharbourview.com.hk",
  "phone": "+852 2802 0111",
  "opened": "1986年",
  "rooms": 320,
  "district": "灣仔",
  "mtr": "港鐵灣仔站 A1 出口經行人天橋步行 10 分鐘",
  "intro": "灣景國際（The Harbourview）位於灣仔港灣道，1986年開業，擁有 320 間客房，係 YWCA（基督教女青年會）經營嘅 3 星級酒店。緊鄰會展及金紫荊廣場，係經濟型商務住宿首選。",
  "history": "灣景國際由 YWCA 於1986年開業，屬於非牟利機構營運，利潤用作社會服務。",
  "facilities": ["24 小時前台", "商務中心", "會議室", "自助洗衣", "免費 WiFi"],
  "restaurants": ["Harbour Café — 全日餐廳", "Lobby Lounge"],
  "rooms_info": "320 間客房，面積由 18 平方米（Standard）至 38 平方米（Harbour Suite）。房間基本但整潔，部分可賞維港景。",
  "price_range": "Standard Room HK$780 起 · Harbour View HK$1,280 起 · Suite HK$2,380 起",
  "nearby": ["香港會議展覽中心（步行 5 分鐘）", "金紫荊廣場（步行 3 分鐘）", "君悅酒店（步行 3 分鐘）", "灣仔碼頭（步行 5 分鐘）", "太古廣場（步行 15 分鐘）"],
  "tips": "灣景國際由 YWCA 經營，非牟利性質，價錢比同區君悅、港麗抵約 50-70%，但設施較基本。會展期及書展期間極快爆滿。",
  "faq": [
    ["灣景國際由邊個經營？", "由 YWCA（基督教女青年會）1986年起經營，非牟利機構，盈利用作社會服務。"],
    ["灣景國際點去會展？", "步行 5 分鐘經行人天橋到會議展覽中心。"],
    ["灣景國際幾錢？", "Standard HK$780 起、Harbour View HK$1,280 起、Suite HK$2,380 起。灣仔經濟之選。"],
    ["有泳池嗎？", "無。基本商務酒店無泳池。如要揀同區皇悅、港麗。"],
    ["灣景國際同君悅差別？", "君悅係 5 星級（HK$2,400 起），灣景係 3 星級（HK$780 起），價差 3 倍但兩者步行 3 分鐘。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"]
  ]
},
"hotel-ease-access-tsuen-wan": {
  "name": "香港荃灣絲麗酒店（悠庭） Hotel Ease Access Tsuen Wan",
  "en": "Hotel Ease Access Tsuen Wan",
  "address_zh": "香港新界荃灣沙咀道51-57號",
  "address_en": "51-57 Sha Tsui Road, Tsuen Wan, New Territories, Hong Kong",
  "lat": 22.3722, "lng": 114.1165,
  "official": "https://www.hoteleaseaccesshk.com",
  "phone": "+852 2940 2222",
  "opened": "2019年",
  "rooms": 287,
  "district": "荃灣",
  "mtr": "港鐵荃灣站 B1 出口步行 8 分鐘",
  "intro": "香港荃灣絲麗酒店悠庭（Hotel Ease Access Tsuen Wan）位於荃灣沙咀道，2019年開業，擁有 287 間客房，係絲麗酒店集團旗下 3 星級酒店，定位年輕背包客及家庭。",
  "history": "絲麗酒店集團（Silka）係香港本地品牌，荃灣絲麗悠庭2019年開業，係集團較新分店。",
  "facilities": ["24 小時前台", "健身中心", "商務中心", "自助洗衣", "免費 WiFi", "免費早餐（部分套餐）"],
  "restaurants": ["Ease Café — 全日餐廳"],
  "rooms_info": "287 間客房，面積由 16 平方米（Economy）至 30 平方米（Family Room）。新設計年輕現代，部分房可賞城市景。",
  "price_range": "Economy Room HK$480 起 · Standard HK$680 起 · Family Room HK$980 起",
  "nearby": ["荃灣廣場（步行 5 分鐘）", "愉景新城（步行 12 分鐘）", "三棟屋博物館（步行 8 分鐘）", "如心酒店（步行 5 分鐘）", "荃新天地（步行 8 分鐘）"],
  "tips": "絲麗悠庭荃灣係同區較新及平嘅選擇，房間雖細但整潔。預算有限嘅背包客或短期商務客首選。免費早餐套餐性價比高。",
  "faq": [
    ["絲麗悠庭點去？", "港鐵荃灣站 B1 出口沿沙咀道步行 8 分鐘。"],
    ["絲麗悠庭幾錢？", "Economy HK$480 起、Standard HK$680 起、Family Room HK$980 起。荃灣最抵選擇之一。"],
    ["絲麗有幾間酒店？", "絲麗（Silka）集團在港有 5 間：荃灣（悠庭）、旺角、上環、西九龍、大埔。帝盛集團附屬品牌。"],
    ["絲麗悠庭適合親子？", "適合預算有限嘅家庭。Family Room 30 平方米可住 3 人，近荃灣廣場商場有兒童設施。"],
    ["有泳池嗎？", "無。經濟型酒店無泳池。想要可揀同區如心酒店。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"]
  ]
},
"disneys-hollywood-hotel": {
  "name": "迪士尼荷里活酒店 Disney's Hollywood Hotel",
  "en": "Disney's Hollywood Hotel",
  "address_zh": "香港大嶼山香港迪士尼樂園度假區",
  "address_en": "Hong Kong Disneyland Resort, Lantau Island, Hong Kong",
  "lat": 22.3140, "lng": 114.0402,
  "official": "https://www.hongkongdisneyland.com/hotels/disneys-hollywood-hotel",
  "phone": "+852 3510 5000",
  "opened": "2005年",
  "rooms": 600,
  "district": "大嶼山/迪士尼",
  "mtr": "港鐵迪士尼綫迪士尼站，酒店穿梭巴士 5 分鐘",
  "intro": "迪士尼荷里活酒店（Disney's Hollywood Hotel）位於香港迪士尼度假區，2005年開業，擁有 600 間客房，係迪士尼 3 間酒店中最經濟嘅選擇。主題為「荷里活黃金時代」，大堂設鋼琴造型泳池、電影主題裝飾。",
  "history": "荷里活酒店2005年與迪士尼樂園同步開業，定位 3 星級、價錢較迪士尼樂園酒店抵 30-40%，適合預算有限嘅家庭。",
  "facilities": ["鋼琴造型室外泳池", "米奇造型噴水池", "Kids Club", "健身中心", "24 小時往返樂園穿梭巴士"],
  "restaurants": ["Chef Mickey — 自助餐（米奇見面）", "Hollywood & Dine — 快餐式美食廣場", "Studio Lounge — 酒吧"],
  "rooms_info": "600 間客房，面積由 30 平方米至 74 平方米。電影主題裝飾，配備迪士尼床品、玩偶、主題浴袍。",
  "price_range": "Standard Room HK$1,680 起 · Sea View HK$2,200 起 · Family Suite HK$3,800 起",
  "nearby": ["香港迪士尼樂園（穿梭巴士 5 分鐘）", "迪欣湖活動中心（步行 5 分鐘）", "迪士尼樂園酒店（步行 10 分鐘）", "機場（的士 15 分鐘）", "東涌（港鐵 10 分鐘）"],
  "tips": "荷里活酒店係迪士尼三間中最抵嘅選擇，家庭套房可住 4 人，平均 HK$950／人。Chef Mickey 自助早餐有角色見面，適合小朋友。",
  "faq": [
    ["荷里活酒店 vs 迪士尼樂園酒店？", "荷里活 3 星、HK$1,680 起、荷里活主題；迪士尼樂園酒店 5 星、HK$2,200 起、維多利亞風。家庭預算有限揀荷里活，追求奢華揀樂園。"],
    ["荷里活酒店去樂園？", "免費穿梭巴士 5 分鐘；或步行 15 分鐘經迪欣湖。"],
    ["荷里活幾錢？", "Standard HK$1,680 起、Sea View HK$2,200 起、Family Suite HK$3,800 起。"],
    ["Chef Mickey 自助餐有乜？", "自助早餐可同米奇、美妮、高飛等角色見面合照。每位約 HK$388-488，住客優惠。需預約。"],
    ["荷里活酒店適合親子嗎？", "最適合。迪士尼主題設計、Kids Club、鋼琴泳池、角色見面餐，小朋友喜愛。"],
    ["check-in 時間？", "Check-in：下午 3:00；Check-out：上午 11:00。"]
  ]
},
"dorsett-tsuen-wan": {
  "name": "香港荃灣帝盛酒店 Dorsett Tsuen Wan",
  "en": "Dorsett Tsuen Wan, Hong Kong",
  "address_zh": "香港新界荃灣沙咀道80號",
  "address_en": "80 Sha Tsui Road, Tsuen Wan, New Territories, Hong Kong",
  "lat": 22.3728, "lng": 114.1175,
  "official": "https://www.tsuenwan.dorsetthotels.com",
  "phone": "+852 3996 2888",
  "opened": "2019年",
  "rooms": 546,
  "district": "荃灣",
  "mtr": "港鐵荃灣站 B1 出口步行 8 分鐘；荃灣西站步行 12 分鐘",
  "intro": "香港荃灣帝盛酒店（Dorsett Tsuen Wan, Hong Kong）位於荃灣沙咀道，2019年開業，擁有 546 間客房，係帝盛集團最新同最大嘅分店。4 星級，設戶外泳池、會議廳，近愉景新城及荃灣廣場。",
  "history": "荃灣帝盛2019年開業，係帝盛集團在港第 5 間酒店。",
  "facilities": ["戶外恆溫泳池", "24 小時健身中心", "會議廳", "商務中心", "免費 Handy 智能手機", "免費穿梭巴士"],
  "restaurants": ["Grand Café — 全日自助餐", "Lobby Bar"],
  "rooms_info": "546 間客房，面積由 22 平方米至 65 平方米。現代商務風格，配備 Smart TV、Handy 智能手機。",
  "price_range": "Deluxe Room HK$880 起 · Executive Room HK$1,280 起 · Suite HK$2,480 起",
  "nearby": ["荃灣廣場（步行 5 分鐘）", "愉景新城（步行 15 分鐘）", "三棟屋博物館（步行 10 分鐘）", "如心酒店（步行 3 分鐘）", "荃新天地（步行 8 分鐘）"],
  "tips": "荃灣帝盛 2019 開業係全區最新帝盛，設施最現代。免費穿梭巴士往機場／中環／尖沙咀方便。適合中等預算嘅商務及親子。",
  "faq": [
    ["荃灣帝盛點去？", "港鐵荃灣站 B1 出口沿沙咀道步行 8 分鐘；荃灣西站步行 12 分鐘。"],
    ["荃灣帝盛幾錢？", "Deluxe HK$880 起、Executive HK$1,280 起、Suite HK$2,480 起。"],
    ["荃灣帝盛有泳池？", "有。戶外恆溫泳池，6:30-22:00，住客免費。"],
    ["荃灣帝盛 vs 如心點揀？", "帝盛較新（2019）、房較大（22平方米起 vs 如心18平方米）；如心較抵（HK$680 起 vs 帝盛 HK$880 起）。預算有限揀如心，追求新設施揀帝盛。"],
    ["帝盛 Handy 手機？", "有。每間房配 Handy 智能手機，4G 上網、本地及國際通話全免費。"],
    ["check-in 時間？", "Check-in：下午 2:00；Check-out：中午 12:00。"]
  ]
}
}

for slug,d in DATA.items():
    Path(f'pages/hotels/{slug}.html').write_text(top5.render(slug,d),encoding='utf-8')
    print('ok',slug)
