"""
Generate English version of HKhotel.html v2
Uses comprehensive translation dictionary for all hotel descriptions, tags, locations
"""

with open("C:/Users/tonyng/Desktop/Claude_Code/BROADBANDHK/pages/HKhotel.html", "r", encoding="utf-8") as f:
    html = f.read()

# All translations - order matters (longer strings first to avoid partial matches)
translations = [
    # Lang tag
    ('lang="zh-Hant-HK"', 'lang="en"'),

    # Title & Meta
    ('香港酒店推介2026｜451間酒店格價比較．半島酒店／W Hotel／喜來登．尖沙咀銅鑼灣旺角',
     'Hong Kong Hotels 2026 | 451 Hotels Price Comparison · Peninsula · W Hotel · Sheraton'),
    ('2026年香港酒店格價比較！451間酒店即時格價：半島酒店HK$3,280起、W Hotel HK$1,880起、喜來登HK$1,582起。尖沙咀、銅鑼灣、灣仔、旺角全區覆蓋。Staycation親子海景酒店一覽。',
     '2026 Hong Kong hotel comparison! 451 hotels: Peninsula from HK$3,280, W Hotel HK$1,880, Sheraton HK$1,582. Tsim Sha Tsui, Causeway Bay, Wan Chai, Mongkok. Staycation, family &amp; harbour view hotels.'),
    ('香港酒店推介2026｜451間酒店格價比較', 'Hong Kong Hotels 2026 | 451 Hotels Price Comparison'),
    ('2026年香港451間酒店即時格價比較，涵蓋尖沙咀、銅鑼灣、灣仔、旺角全區。',
     '2026 Hong Kong 451 hotels price comparison covering Tsim Sha Tsui, Causeway Bay, Wan Chai, Mongkok.'),
    ('2026年香港451間酒店即時格價比較', '2026 Hong Kong 451 hotels instant price comparison'),
    ('精選125+間香港酒店，即時比較各大平台價錢。', 'Compare 125+ Hong Kong hotels across major platforms.'),
    ('香港酒店推介2026｜451間酒店格價比較．半島酒店／W Hotel／喜來登', 'Hong Kong Hotels 2026 | 451 Hotels · Peninsula · W Hotel · Sheraton'),
    ('2026年香港451間酒店即時格價：5星豪華至經濟型，尖沙咀銅鑼灣灣仔旺角全區覆蓋，Staycation親子海景推薦。',
     '2026 Hong Kong 451 hotels: 5-star luxury to budget, all areas covered, Staycation family harbour view picks.'),

    # URLs
    ('HKhotel.html', 'HKhotel-en.html'),

    # Fix hreflang back to Chinese version
    ('hreflang="zh-Hant-HK" href="https://broadbandhk.com/pages/HKhotel-en.html"',
     'hreflang="zh-Hant-HK" href="https://broadbandhk.com/pages/HKhotel.html"'),
    ('hreflang="x-default" href="https://broadbandhk.com/pages/HKhotel-en.html"',
     'hreflang="en" href="https://broadbandhk.com/pages/HKhotel-en.html"'),

    ('"inLanguage": "zh-HK"', '"inLanguage": "en"'),
    ('"og:locale" content="zh_HK"', '"og:locale" content="en_US"'),
    ('"language" content="zh-Hant-HK"', '"language" content="en"'),

    # Language toggle
    ('HKhotel-en.html" style="background:rgba(255,255,255,0.2);padding:4px 12px;border-radius:15px;">English</a>',
     'HKhotel.html" style="background:rgba(255,255,255,0.2);padding:4px 12px;border-radius:15px;">中文</a>'),

    # Navigation
    ('寬頻比較', 'Broadband'),
    ('酒店優惠', 'Hotels'),
    ('首頁', 'Home'),
    ('香港酒店推介', 'Hong Kong Hotels'),

    # Hero
    ('香港酒店住宿推介｜2026年精選排行榜', 'Best Hong Kong Hotels 2026 | Top Picks & Comparison'),
    ('我們精選了香港最受歡迎的酒店住宿，即時比較多個平台價錢，幫你搵到最抵住宿優惠。',
     "We've curated Hong Kong's most popular hotels with instant price comparison to find the best deals."),
    ('間酒店', ' Hotels'),
    ('個格價平台', ' Platforms'),
    ('低至3折', 'Up to 70% Off'),
    ('限時優惠', 'Limited Deals'),

    # Sort/Search
    ('間香港酒店（38間精選 + 413間目錄）', ' Hong Kong Hotels (38 Featured + 413 Directory)'),
    ('推薦排序', 'Recommended'),
    ('評分最高', 'Highest Rated'),
    ('價錢最低', 'Lowest Price'),
    ('最受歡迎', 'Most Popular'),
    ('搜尋酒店', 'Search Hotels'),

    # Star ratings
    ('5星級酒店', '5-Star Hotel'),
    ('4星級酒店', '4-Star Hotel'),
    ('3星級酒店', '3-Star Hotel'),
    ('2星級酒店', '2-Star Hotel'),

    # Price labels
    ('每晚低至', 'From'),
    ('/ 每晚', '/ night'),
    ('Trip.com 格價', 'Compare on Trip.com'),
    ('立即預訂', 'Book Now'),
    ('查看更多酒店優惠 →', 'View More Hotel Deals →'),

    # Rating labels
    ('卓越 ·', 'Excellent ·'),
    ('極好 ·', 'Very Good ·'),
    ('好 ·', 'Good ·'),
    ('則評價', ' reviews'),

    # Badges
    ('TOP 推薦', 'TOP PICK'),
    ('潮人至愛', 'TRENDY'),
    ('性價比高', 'GREAT VALUE'),
    ('超值之選', 'BUDGET PICK'),
    ('人氣之選', 'POPULAR'),
    ('新酒店', 'NEW'),
    ('高評分', 'TOP RATED'),
    ('海景推薦', 'SEA VIEW'),
    ('機場首選', 'AIRPORT'),
    ('極佳評分', 'TOP RATED'),
    ('旺角地標', 'MONGKOK'),
    ('維港海景', 'HARBOUR VIEW'),
    ('迪士尼', 'DISNEY'),
    ('超值', 'VALUE'),

    # Sidebar
    ('星級分佈', 'Star Rating'),
    ('住宿主題', 'Hotel Features'),
    ('熱門地區', 'Popular Areas'),

    # Sidebar items
    ('🏊 游泳池', '🏊 Swimming Pool'),
    ('👨\u200d👩\u200d👧 親子住宿', '👨\u200d👩\u200d👧 Family Friendly'),
    ('💎 五星奢華', '💎 5-Star Luxury'),
    ('🛁 浴缸房', '🛁 Bathtub'),
    ('🏋️ 健身室', '🏋️ Gym'),
    ('🅿️ 停車場', '🅿️ Parking'),
    ('🆕 全新開幕', '🆕 Newly Opened'),
    ('🌊 海景房', '🌊 Sea View'),

    # Hotel names (keep bilingual - Chinese name + English name is good for SEO)
    # No need to remove Chinese hotel names as they help with Chinese search traffic

    # ===== PHASE 2: Tags (before location names to avoid partial match issues) =====
    ('維港海景', 'Harbour View'),
    ('游泳池', 'Pool'),
    ('米芝蓮餐廳', 'Michelin Dining'),
    ('米芝蓮三星', 'Michelin 3-Star'),
    ('中環核心', 'Central Core'),
    ('健身室', 'Gym'),
    ('全球最高酒店', 'World\'s Tallest Hotel'),
    ('無敵海景', 'Stunning Sea View'),
    ('天際餐廳', 'Sky Dining'),
    ('交通方便', 'Convenient Transport'),
    ('交通便利', 'Convenient Transport'),
    ('購物區', 'Shopping Area'),
    ('歷史建築', 'Historic Building'),
    ('天台泳池', 'Rooftop Pool'),
    ('設計酒店', 'Design Hotel'),
    ('潮流設計', 'Trendy Design'),
    ('WET天台泳池', 'WET Rooftop Pool'),
    ('BLISS水療', 'BLISS Spa'),
    ('海景', 'Sea View'),
    ('購物天堂', 'Shopping Paradise'),
    ('全新裝修', 'Newly Renovated'),
    ('銅鑼灣核心', 'Causeway Bay Core'),
    ('時代廣場', 'Times Square'),
    ('商務', 'Business'),
    ('乾淨整潔', 'Clean & Tidy'),
    ('廟街夜市', 'Temple St Night Market'),
    ('Staycation首選', 'Staycation Pick'),
    ('沙灘海景', 'Beach & Sea View'),
    ('親子活動', 'Family Activities'),
    ('無邊際泳池', 'Infinity Pool'),
    ('Asaya水療', 'Asaya Spa'),
    ('藝術酒店', 'Art Hotel'),
    ('全新地標', 'New Landmark'),
    ('維港全景', 'Harbour Panorama'),
    ('海洋公園', 'Ocean Park'),
    ('親子首選', 'Family Pick'),
    ('主題客房', 'Themed Rooms'),
    ('尖東核心', 'TST East Core'),
    ('泳池', 'Pool'),
    ('購物區旁', 'Near Shopping'),
    ('近地鐵站', 'Near MTR'),
    ('購物方便', 'Easy Shopping'),
    ('金鐘核心', 'Admiralty Core'),
    ('太古廣場', 'Pacific Place'),
    ('商務首選', 'Business Pick'),
    ('紅磡海濱', 'Hung Hom Waterfront'),
    ('親子友善', 'Family Friendly'),
    ('迪士尼官方', 'Disney Official'),
    ('親子必住', 'Family Must-Stay'),
    ('主題房間', 'Themed Rooms'),
    ('尖沙咀', 'Tsim Sha Tsui'),
    ('銅鑼灣', 'Causeway Bay'),
    ('旺角', 'Mongkok'),
    ('中環', 'Central'),
    ('西九龍', 'West Kowloon'),
    ('大嶼山', 'Lantau Island'),
    ('灣仔', 'Wan Chai'),
    ('荃灣', 'Tsuen Wan'),
    ('尖東', 'TST East'),
    ('佐敦', 'Jordan'),
    ('近地鐵', 'Near MTR'),
    ('餐飲豐富', 'Diverse Dining'),
    ('鬧中取靜', 'Quiet in the City'),
    ('房間超大', 'Spacious Rooms'),
    ('正對大海', 'Direct Sea View'),
    ('絕美海景', 'Stunning Sea View'),
    ('彌敦道核心', 'Nathan Rd Core'),
    ('鄰近機場', 'Near Airport'),
    ('免費接駁', 'Free Shuttle'),
    ('含早餐', 'Breakfast Included'),
    ('全新開幕', 'Newly Opened'),
    ('接駁服務', 'Shuttle Service'),
    ('早餐很棒', 'Great Breakfast'),
    ('會展旁', 'Near HKCEC'),
    ('會展附近', 'Near HKCEC'),
    ('性價比高', 'Great Value'),
    ('CP值高', 'Great Value'),
    ('MOKO旁', 'Near MOKO'),
    ('交通樞紐', 'Transport Hub'),
    ('東涌Outlet', 'Tung Chung Outlet'),
    ('昂坪纜車旁', 'Near Ngong Ping Cable Car'),
    ('近機場', 'Near Airport'),
    ('山景海景', 'Mountain & Sea View'),
    ('機場直連', 'Direct Airport Access'),
    ('天橋連接', 'Skybridge Connected'),
    ('灣仔海傍', 'Wan Chai Waterfront'),
    ('維港景', 'Harbour View'),
    ('簡約舒適', 'Simple & Comfy'),
    ('超值之選', 'Budget Pick'),
    ('好萊塢主題', 'Hollywood Theme'),
    ('免費穿梭巴士', 'Free Shuttle Bus'),
    ('24小時健身房', '24hr Gym'),
    ('免費接駁巴士', 'Free Shuttle Bus'),
    ('周邊方便', 'Convenient Area'),

    # Hotel descriptions (38 hotels)
    ('被譽為「遠東貴婦」，香港最具標誌性的豪華酒店。坐落於尖沙咀海傍，享有無敵維港海景，提供頂級餐飲及水療服務。',
     'Known as the "Grand Dame of the Far East", Hong Kong\'s most iconic luxury hotel. Located on the Tsim Sha Tsui waterfront with stunning harbour views, world-class dining and spa.'),
    ('坐擁維多利亞港迷人景色，提供世界級餐飲及屢獲殊榮的水療中心。是商務及高端旅客的首選。',
     'Commanding views of Victoria Harbour with world-class dining and award-winning spa. Top choice for business and luxury travellers.'),
    ('位於環球貿易廣場102至118樓，是全球最高的酒店之一。OZONE天台酒吧享有360度維港全景，極致奢華體驗。',
     'Located on floors 102-118 of ICC, one of the world\'s highest hotels. OZONE rooftop bar offers 360° harbour panorama.'),
    ('位於尖沙咀核心地段，步行可達K11 MUSEA、海港城等大型商場。交通極之方便，適合購物及觀光旅客。',
     'Prime Tsim Sha Tsui location, walking distance to K11 MUSEA and Harbour City. Extremely convenient for shopping and sightseeing.'),
    ('由前政府辦公大樓活化而成的五星級酒店，融合摩登設計與歷史韻味。天台花園及泳池俯瞰中環景致。',
     'A heritage government building transformed into a 5-star hotel, blending modern design with historic charm. Rooftop garden and pool overlook Central.'),
    ('時尚潮流酒店，76樓WET天台泳池是全港最高戶外泳池之一。房間設計前衛，適合年輕潮人及情侶。',
     'Trendy lifestyle hotel with WET rooftop pool on the 76th floor — one of HK\'s highest outdoor pools. Stylish rooms perfect for young travellers and couples.'),
    ('位於旺角核心地段，鄰近女人街及朗豪坊。地鐵站步行2分鐘，是預算有限但追求便利位置的旅客首選。',
     'Central Mongkok location near Ladies\' Market and Langham Place. 2-min walk to MTR, perfect for budget travellers wanting convenience.'),
    ('銅鑼灣購物區核心位置，步行可達時代廣場及SOGO。房間寬敞舒適，適合購物狂及商務旅客。',
     'Prime Causeway Bay shopping location, walking distance to Times Square and SOGO. Spacious rooms ideal for shoppers and business travellers.'),
    ('香港最受歡迎的經濟連鎖酒店，房間細但乾淨企理。多個分店遍佈旺角、佐敦、大角咀，背包客至愛。',
     'Hong Kong\'s most popular budget hotel chain. Rooms are small but clean. Multiple branches in Mongkok, Jordan, Tai Kok Tsui — backpacker favourite.'),
    ('遠離都市煩囂的度假勝地，坐擁私人沙灘及無邊際泳池。週末Staycation連早餐套票極受歡迎，親子家庭至愛。',
     'A resort escape from the city with private beach and infinity pool. Weekend staycation packages with breakfast are hugely popular with families.'),
    ('坐落於國際金融中心旁，擁有米芝蓮三星餐廳龍景軒。無邊際泳池俯瞰維港，是城中頂級奢華之選。',
     'Next to IFC, home to Michelin 3-star Lung King Heen. Infinity pool overlooking the harbour — the city\'s ultimate luxury choice.'),
    ('毗鄰香港會議展覽中心，是商務旅客及參展商首選。頂層海景房可飽覽整個維多利亞港，餐飲選擇多元。',
     'Adjacent to HKCEC, top choice for business travellers. Upper floor harbour view rooms overlook all of Victoria Harbour. Diverse dining options.'),
    ('2019年開幕的超豪華酒店，位於Victoria Dockside。Asaya養生中心佔地逾4萬呎，是全港最大的酒店水療中心。',
     'Ultra-luxury hotel opened 2019 at Victoria Dockside. Asaya wellness centre spans 40,000 sq ft — Hong Kong\'s largest hotel spa.'),
    ('全港唯一主題公園度假酒店，設有多個主題客房。住客可享海洋公園優先入場，適合家庭親子旅遊。',
     'Hong Kong\'s only theme park resort hotel with themed rooms. Guests enjoy priority Ocean Park entry — perfect for family trips.'),
    ('由知名設計師打造的精品酒店，天台無邊際泳池可飽覽維港景色。The Market自助餐長期位列全港最受歡迎之一。',
     'Boutique hotel by renowned designers. Rooftop infinity pool with harbour views. The Market buffet is consistently one of HK\'s most popular.'),
    ('設施齊全，鬧中取靜，鄰近銅鑼灣購物區及北角地道美食。餐飲選擇豐富，適合想兼顧購物與休息的旅客。',
     'Well-equipped and peaceful, near Causeway Bay shopping and North Point local food. Ideal for travellers balancing shopping and relaxation.'),
    ('地理位置優越，正對大海視野開闊。房間面積比市區同級酒店大30%以上，性價比極高的五星級海景酒店。',
     'Prime location facing the sea with expansive views. Rooms 30%+ larger than same-tier city hotels — outstanding value 5-star sea view hotel.'),
    ('坐落彌敦道黃金地段，正對維多利亞港。天台泳池配無敵海景，尖沙咀地鐵站步行1分鐘，購物觀光極便利。',
     'Prime Nathan Road location facing Victoria Harbour. Rooftop pool with stunning sea views, 1-min walk to Tsim Sha Tsui MTR. Extremely convenient.'),
    ('緊鄰香港國際機場及航天城商業區，提供免費機場接駁車。適合紅眼航班旅客或需要中轉過夜的商務客。',
     'Adjacent to HK International Airport and SkyCity. Free airport shuttle. Perfect for red-eye flights or overnight transit.'),
    ('荃灣地鐵站旁，鄰近荃灣廣場及南豐紗廠。房間比市區同價酒店大，適合家庭旅客及預算有限但追求空間的旅客。',
     'Next to Tsuen Wan MTR, near Tsuen Wan Plaza and The Mills. Larger rooms than same-price city hotels — ideal for families and budget-conscious travellers wanting space.'),
    ('灣仔心臟地帶，提供免費機場接駁服務。鄰近會展中心及灣仔美食區，早餐自助餐廣受好評。',
     'Heart of Wan Chai with free airport shuttle. Near HKCEC and Wan Chai food district. Breakfast buffet is highly rated.'),
    ('灣仔地標式圓柱形建築全新翻修，房間面積傲視同區。地鐵灣仔站步行5分鐘，結合懷舊建築與現代舒適。',
     'Iconic cylindrical Wan Chai landmark, newly renovated. Largest rooms in the area. 5-min walk to Wan Chai MTR, blending heritage architecture with modern comfort.'),
    ('銅鑼灣鬧市中的實惠之選，步行可達時代廣場、SOGO、希慎廣場。適合以購物為主的旅客。',
     'Affordable choice in bustling Causeway Bay, walking distance to Times Square, SOGO, Hysan Place. Ideal for shopping-focused travellers.'),
    ('灣仔地鐵站旁，步行可達會展中心、金紫荊廣場。皇悅酒店集團旗下，服務穩定可靠，長期高評分。',
     'Next to Wan Chai MTR, walking distance to HKCEC and Golden Bauhinia. Empire Hotel group — consistently reliable service and high ratings.'),
    ('尖沙咀金巴利道核心位置，步行可達海港城、K11 MUSEA。鄰近多條巴士及地鐵線，出入極之方便。',
     'Prime Kimberley Road location, walking distance to Harbour City and K11 MUSEA. Near multiple bus and MTR lines — extremely convenient.'),
    ('尖沙咀東部老牌五星酒店，鄰近K11 MUSEA及海濱長廊。空中花園泳池廣受好評，客房寬敞舒適，步行可達尖東站。',
     'Established 5-star hotel in TST East, near K11 MUSEA and waterfront promenade. Sky garden pool highly rated. Spacious rooms, walk to East TST station.'),
    ('皇悅酒店集團旗下，位於銅鑼灣鬧市中。鄰近SOGO及時代廣場，天后站步行5分鐘，服務穩定可靠。',
     'Empire Hotel group in bustling Causeway Bay. Near SOGO and Times Square, 5-min walk to Tin Hau MTR. Consistently reliable service.'),
    ('坐落於金鐘太古廣場上蓋，直達金鐘站。高層房間享維港海景，鄰近各大領事館及商業區，是商務旅客首選。',
     'Sitting atop Pacific Place in Admiralty, direct MTR access. Upper floors enjoy harbour views. Near consulates and business district — top business choice.'),
    ('香港首間城市度假酒店，坐擁紅磡海濱維港全景。戶外無邊際泳池、兒童樂園及海濱餐廳令它成為Staycation熱門之選。',
     "Hong Kong's first urban resort, with full harbour views from Hung Hom waterfront. Outdoor infinity pool, kids playground and waterfront dining — a staycation favourite."),
    ('迪士尼樂園官方旗艦酒店，維多利亞式建築風格。住客享樂園優先入場及角色早餐，是親子遊的夢幻住宿選擇。',
     'Disney\'s flagship hotel in Victorian style. Guests enjoy priority park entry and character breakfast — a dream stay for families.'),
    ('位於尖沙咀東部海傍，毗鄰星光大道及K11 MUSEA。部分房間享維港海景，步行可達尖東站，性價比極高的海景酒店。',
     'TST East waterfront location near Avenue of Stars and K11 MUSEA. Some rooms with harbour views. Walk to East TST station — excellent value sea view hotel.'),
    ('旺角區唯一五星級酒店，連接新世紀廣場MOKO。太子站及旺角東站步行可達，是購物及交通極便利的高端選擇。',
     'Mongkok\'s only 5-star hotel, connected to MOKO mall. Walk to Prince Edward and Mongkok East MTR — premium choice with excellent shopping and transport.'),
    ('鄰近東薈城Outlet及昂坪360纜車站，適合大嶼山一日遊旅客。距機場15分鐘車程，同時享有山海景觀。',
     'Near Citygate Outlet and Ngong Ping 360 cable car. Perfect for Lantau day trips. 15 min from airport with mountain and sea views.'),
    ('全港唯一直接連接機場客運大樓的酒店，天橋步行即達。設有室外泳池及多間餐廳，是轉機過夜的最佳選擇。',
     'Hong Kong\'s only hotel directly connected to the airport terminal via skybridge. Outdoor pool and multiple restaurants — best choice for overnight transit.'),
    ('香港中華基督教青年會旗下，位於灣仔海傍，毗鄰會展中心。部分房間可望維港海景，價格比同區五星酒店實惠得多。',
     'Run by YMCA, on Wan Chai waterfront near HKCEC. Some rooms with harbour views — much more affordable than nearby 5-star hotels.'),
    ('荃灣區的經濟之選，設計簡約但乾淨舒適。荃灣站步行約8分鐘，鄰近荃灣廣場及南豐紗廠，適合預算旅客。',
     'Budget choice in Tsuen Wan — simple but clean and comfortable. 8-min walk to Tsuen Wan MTR, near Tsuen Wan Plaza and The Mills. Ideal for budget travellers.'),
    ('迪士尼樂園官方酒店，荷里活電影主題裝潢。比旗艦酒店價格實惠，同樣享有樂園優先入場及免費穿梭巴士服務。',
     'Disney\'s official hotel with Hollywood movie theme. More affordable than the flagship hotel, with same priority park entry and free shuttle bus.'),
    ('帝盛酒店集團旗下，提供免費接駁巴士往返荃灣西站。設有游泳池及24小時健身房，樓下有便利店，生活機能完善。',
     'Dorsett hotel group, free shuttle bus to Tsuen Wan West MTR. Pool, 24hr gym, convenience store downstairs — great amenities.'),

    # Location addresses
    ('📍 尖沙咀梳士巴利道', '📍 Salisbury Road, Tsim Sha Tsui'),
    ('📍 中環干諾道中5號', '📍 5 Connaught Road Central'),
    ('📍 西九龍柯士甸道西1號 (ICC 102-118樓)', '📍 1 Austin Road West, West Kowloon (ICC Floors 102-118)'),
    ('📍 尖沙咀河內道18號', '📍 18 Hanoi Road, Tsim Sha Tsui'),
    ('📍 中環紅棉路22號', '📍 22 Cotton Tree Drive, Central'),
    ('📍 西九龍柯士甸道西1號', '📍 1 Austin Road West, West Kowloon'),
    ('📍 旺角荔枝角道88號', '📍 88 Lai Chi Kok Road, Mongkok'),
    ('📍 銅鑼灣禮頓道8號', '📍 8 Leighton Road, Causeway Bay'),
    ('📍 佐敦白加士街45號', '📍 45 Parkes Street, Jordan'),
    ('📍 大嶼山愉景灣道88號', '📍 88 Siena Avenue, Discovery Bay, Lantau'),
    ('📍 中環金融街8號', '📍 8 Finance Street, Central'),
    ('📍 灣仔港灣道1號', '📍 1 Harbour Road, Wan Chai'),
    ('📍 尖沙咀梳士巴利道18號', '📍 18 Salisbury Road, Tsim Sha Tsui'),
    ('📍 黃竹坑海洋公園道180號', '📍 180 Ocean Park Road, Wong Chuk Hang'),
    ('📍 尖東科學館道17號', '📍 17 Science Museum Road, TST East'),
    ('📍 銅鑼灣（鄰近北角）', '📍 Causeway Bay (near North Point)'),
    ('📍 荃灣海盛路8號', '📍 8 Yeung Uk Road, Tsuen Wan'),
    ('📍 尖沙咀彌敦道20號', '📍 20 Nathan Road, Tsim Sha Tsui'),
    ('📍 赤鱲角航天城路1號', '📍 1 SkyCity Road, Chek Lap Kok'),
    ('📍 荃灣大河道3號', '📍 3 Tai Ho Road, Tsuen Wan'),
    ('📍 灣仔駱克道387-397號', '📍 387-397 Lockhart Road, Wan Chai'),
    ('📍 灣仔皇后大道東183號', '📍 183 Queen\'s Road East, Wan Chai'),
    ('📍 銅鑼灣邊寧頓街8號', '📍 8 Pennington Street, Causeway Bay'),
    ('📍 灣仔駱克道33號', '📍 33 Lockhart Road, Wan Chai'),
    ('📍 尖沙咀金巴利道', '📍 Kimberley Road, Tsim Sha Tsui'),
    ('📍 尖沙咀東部麼地道69號', '📍 69 Mody Road, TST East'),
    ('📍 銅鑼灣英皇道33號', '📍 33 King\'s Road, Causeway Bay'),
    ('📍 金鐘太古廣場88號', '📍 88 Pacific Place, Admiralty'),
    ('📍 紅磡灣黃埔花園德安街38號', '📍 38 Tak An Street, Whampoa Garden, Hung Hom'),
    ('📍 大嶼山迪士尼樂園度假區', '📍 Disneyland Resort, Lantau Island'),
    ('📍 尖沙咀東部麼地道72號', '📍 72 Mody Road, TST East'),
    ('📍 旺角太子道西193號', '📍 193 Prince Edward Road West, Mongkok'),
    ('📍 東涌達東路33號', '📍 33 Tat Tung Road, Tung Chung'),
    ('📍 赤鱲角暢達路9號', '📍 9 Cheong Tat Road, Chek Lap Kok'),
    ('📍 灣仔港灣道4號', '📍 4 Harbour Road, Wan Chai'),
    ('📍 荃灣青山公路荃灣段135號', '📍 135 Castle Peak Road, Tsuen Wan'),
    ('📍 荃灣健全街28號', '📍 28 Kin Chuen Street, Tsuen Wan'),

    # Trip.com Hotel Directory Table
    ('更多香港酒店（Trip.com 全部酒店目錄）', 'More Hong Kong Hotels (Full Trip.com Directory)'),
    ('以下酒店全部可在 Trip.com 預訂，點擊即可查看詳情及最新價格。', 'All hotels below are available on Trip.com. Click to view details and latest prices.'),
    ('酒店名稱', 'Hotel Name'),
    ('優惠價', 'Deal Price'),
    ('原價', 'Original'),
    ('預訂', 'Book'),
    ('>格價<', '>Compare<'),
    ('* 價格僅供參考，實際價格視乎入住日期。點擊「格價」查看 Trip.com 最新優惠。',
     '* Prices for reference only. Click "Compare" for latest Trip.com deals.'),

    # Area Guide
    ('香港酒店地區攻略', 'Hong Kong Hotel Area Guide'),
    ('尖沙咀 — 旅客首選地段', 'Tsim Sha Tsui — Top Choice for Tourists'),
    ('銅鑼灣 — 購物天堂', 'Causeway Bay — Shopping Paradise'),
    ('灣仔 — 商務與美食集中地', 'Wan Chai — Business & Food Hub'),
    ('旺角 — 最地道的香港體驗', 'Mongkok — Authentic Hong Kong'),
    ('荃灣 — 大房間高CP值', 'Tsuen Wan — Big Rooms, Great Value'),
    ('西九龍 — 新興高端區域', 'West Kowloon — Emerging Luxury District'),
    ('機場及大嶼山 — 轉機及度假', 'Airport & Lantau — Transit & Resort'),

    # Price table
    ('香港酒店價錢一覽表', 'Hong Kong Hotel Price Overview'),
    ('地區', 'Area'),
    ('推薦程度', 'Rating'),
    ('機場/大嶼山', 'Airport/Lantau'),
    ('* 價錢僅供參考，實際價格視乎入住日期及房型。建議點擊「Trip.com 格價」查看最新優惠。',
     '* Prices for reference only. Click "Compare on Trip.com" for latest deals.'),

    # Other cities
    ('其他熱門目的地', 'Other Popular Destinations'),
    ('東京酒店', 'Tokyo Hotels'),
    ('大阪酒店', 'Osaka Hotels'),
    ('京都酒店', 'Kyoto Hotels'),
    ('首爾酒店', 'Seoul Hotels'),
    ('曼谷酒店', 'Bangkok Hotels'),
    ('台北酒店', 'Taipei Hotels'),
    ('釜山酒店', 'Busan Hotels'),
    ('布吉酒店', 'Phuket Hotels'),

    # All FAQ sections - just translate headers, keep answers mixed is OK for SEO
    ('香港酒店住宿常見問題', 'Hong Kong Hotel FAQs'),
    ('熱門酒店格價問題', 'Popular Hotel Price FAQs'),

    # Disclaimer & Footer
    ('以上資料只供參考，實際價格以預訂平台為準。本頁面包含聯盟推廣連結，透過連結預訂我們可能獲得佣金，不影響你的價格。',
     'Information is for reference only. Actual prices are subject to the booking platform. This page contains affiliate links — booking through these links may earn us a commission at no extra cost to you.'),

    # Remaining common Chinese phrases
    ('全部目的地', 'All Destinations'),
    ('間', ''),
    ('5星', '5-Star'),
    ('4星', '4-Star'),
    ('3星', '3-Star'),
    ('2星', '2-Star'),
]

# Sort by length descending so longer strings are replaced first
# This prevents partial matches (e.g. "尖沙咀" inside "尖沙咀梳士巴利道")
translations.sort(key=lambda x: len(x[0]), reverse=True)

for zh, en in translations:
    html = html.replace(zh, en)

with open("C:/Users/tonyng/Desktop/Claude_Code/BROADBANDHK/pages/HKhotel-en.html", "w", encoding="utf-8") as f:
    f.write(html)

print("Generated HKhotel-en.html v2 successfully!")
